// Generated by gencpp from file arduinobot_contol/AngleConvert.msg
// DO NOT EDIT!


#ifndef ARDUINOBOT_CONTOL_MESSAGE_ANGLECONVERT_H
#define ARDUINOBOT_CONTOL_MESSAGE_ANGLECONVERT_H

#include <ros/service_traits.h>


#include <arduinobot_contol/AngleConvertRequest.h>
#include <arduinobot_contol/AngleConvertResponse.h>


namespace arduinobot_contol
{

struct AngleConvert
{

typedef AngleConvertRequest Request;
typedef AngleConvertResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AngleConvert
} // namespace arduinobot_contol


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arduinobot_contol::AngleConvert > {
  static const char* value()
  {
    return "904e8346ace63ec441f6f58d8efc6687";
  }

  static const char* value(const ::arduinobot_contol::AngleConvert&) { return value(); }
};

template<>
struct DataType< ::arduinobot_contol::AngleConvert > {
  static const char* value()
  {
    return "arduinobot_contol/AngleConvert";
  }

  static const char* value(const ::arduinobot_contol::AngleConvert&) { return value(); }
};


// service_traits::MD5Sum< ::arduinobot_contol::AngleConvertRequest> should match
// service_traits::MD5Sum< ::arduinobot_contol::AngleConvert >
template<>
struct MD5Sum< ::arduinobot_contol::AngleConvertRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arduinobot_contol::AngleConvert >::value();
  }
  static const char* value(const ::arduinobot_contol::AngleConvertRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduinobot_contol::AngleConvertRequest> should match
// service_traits::DataType< ::arduinobot_contol::AngleConvert >
template<>
struct DataType< ::arduinobot_contol::AngleConvertRequest>
{
  static const char* value()
  {
    return DataType< ::arduinobot_contol::AngleConvert >::value();
  }
  static const char* value(const ::arduinobot_contol::AngleConvertRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arduinobot_contol::AngleConvertResponse> should match
// service_traits::MD5Sum< ::arduinobot_contol::AngleConvert >
template<>
struct MD5Sum< ::arduinobot_contol::AngleConvertResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arduinobot_contol::AngleConvert >::value();
  }
  static const char* value(const ::arduinobot_contol::AngleConvertResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduinobot_contol::AngleConvertResponse> should match
// service_traits::DataType< ::arduinobot_contol::AngleConvert >
template<>
struct DataType< ::arduinobot_contol::AngleConvertResponse>
{
  static const char* value()
  {
    return DataType< ::arduinobot_contol::AngleConvert >::value();
  }
  static const char* value(const ::arduinobot_contol::AngleConvertResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDUINOBOT_CONTOL_MESSAGE_ANGLECONVERT_H
