(cl:defpackage arduinobot_remote-msg
  (:use )
  (:export
   "<ARDUINOBOTTASKACTION>"
   "ARDUINOBOTTASKACTION"
   "<ARDUINOBOTTASKACTIONACTION>"
   "ARDUINOBOTTASKACTIONACTION"
   "<ARDUINOBOTTASKACTIONACTIONFEEDBACK>"
   "ARDUINOBOTTASKACTIONACTIONFEEDBACK"
   "<ARDUINOBOTTASKACTIONACTIONGOAL>"
   "ARDUINOBOTTASKACTIONACTIONGOAL"
   "<ARDUINOBOTTASKACTIONACTIONRESULT>"
   "ARDUINOBOTTASKACTIONACTIONRESULT"
   "<ARDUINOBOTTASKACTIONFEEDBACK>"
   "ARDUINOBOTTASKACTIONFEEDBACK"
   "<ARDUINOBOTTASKACTIONGOAL>"
   "ARDUINOBOTTASKACTIONGOAL"
   "<ARDUINOBOTTASKACTIONRESULT>"
   "ARDUINOBOTTASKACTIONRESULT"
   "<ARDUINOBOTTASKFEEDBACK>"
   "ARDUINOBOTTASKFEEDBACK"
   "<ARDUINOBOTTASKGOAL>"
   "ARDUINOBOTTASKGOAL"
   "<ARDUINOBOTTASKRESULT>"
   "ARDUINOBOTTASKRESULT"
  ))

