; Auto-generated. Do not edit!


(cl:in-package arduinobot_remote-msg)


;//! \htmlinclude ArduinobotTaskActionFeedback.msg.html

(cl:defclass <ArduinobotTaskActionFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage
    :reader percentage
    :initarg :percentage
    :type cl:integer
    :initform 0))
)

(cl:defclass ArduinobotTaskActionFeedback (<ArduinobotTaskActionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArduinobotTaskActionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArduinobotTaskActionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arduinobot_remote-msg:<ArduinobotTaskActionFeedback> is deprecated: use arduinobot_remote-msg:ArduinobotTaskActionFeedback instead.")))

(cl:ensure-generic-function 'percentage-val :lambda-list '(m))
(cl:defmethod percentage-val ((m <ArduinobotTaskActionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arduinobot_remote-msg:percentage-val is deprecated.  Use arduinobot_remote-msg:percentage instead.")
  (percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArduinobotTaskActionFeedback>) ostream)
  "Serializes a message object of type '<ArduinobotTaskActionFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'percentage)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArduinobotTaskActionFeedback>) istream)
  "Deserializes a message object of type '<ArduinobotTaskActionFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'percentage) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArduinobotTaskActionFeedback>)))
  "Returns string type for a message object of type '<ArduinobotTaskActionFeedback>"
  "arduinobot_remote/ArduinobotTaskActionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArduinobotTaskActionFeedback)))
  "Returns string type for a message object of type 'ArduinobotTaskActionFeedback"
  "arduinobot_remote/ArduinobotTaskActionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArduinobotTaskActionFeedback>)))
  "Returns md5sum for a message object of type '<ArduinobotTaskActionFeedback>"
  "face31f38d20abbde445df7aa912bb07")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArduinobotTaskActionFeedback)))
  "Returns md5sum for a message object of type 'ArduinobotTaskActionFeedback"
  "face31f38d20abbde445df7aa912bb07")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArduinobotTaskActionFeedback>)))
  "Returns full string definition for message of type '<ArduinobotTaskActionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int64 percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArduinobotTaskActionFeedback)))
  "Returns full string definition for message of type 'ArduinobotTaskActionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int64 percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArduinobotTaskActionFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArduinobotTaskActionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ArduinobotTaskActionFeedback
    (cl:cons ':percentage (percentage msg))
))
