; Auto-generated. Do not edit!


(cl:in-package arduinobot_remote-msg)


;//! \htmlinclude ArduinobotTaskActionResult.msg.html

(cl:defclass <ArduinobotTaskActionResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ArduinobotTaskActionResult (<ArduinobotTaskActionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArduinobotTaskActionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArduinobotTaskActionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arduinobot_remote-msg:<ArduinobotTaskActionResult> is deprecated: use arduinobot_remote-msg:ArduinobotTaskActionResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <ArduinobotTaskActionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arduinobot_remote-msg:success-val is deprecated.  Use arduinobot_remote-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArduinobotTaskActionResult>) ostream)
  "Serializes a message object of type '<ArduinobotTaskActionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArduinobotTaskActionResult>) istream)
  "Deserializes a message object of type '<ArduinobotTaskActionResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArduinobotTaskActionResult>)))
  "Returns string type for a message object of type '<ArduinobotTaskActionResult>"
  "arduinobot_remote/ArduinobotTaskActionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArduinobotTaskActionResult)))
  "Returns string type for a message object of type 'ArduinobotTaskActionResult"
  "arduinobot_remote/ArduinobotTaskActionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArduinobotTaskActionResult>)))
  "Returns md5sum for a message object of type '<ArduinobotTaskActionResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArduinobotTaskActionResult)))
  "Returns md5sum for a message object of type 'ArduinobotTaskActionResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArduinobotTaskActionResult>)))
  "Returns full string definition for message of type '<ArduinobotTaskActionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArduinobotTaskActionResult)))
  "Returns full string definition for message of type 'ArduinobotTaskActionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArduinobotTaskActionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArduinobotTaskActionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ArduinobotTaskActionResult
    (cl:cons ':success (success msg))
))
