arduinobot:
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
  hand_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_4
