// Generated by gencpp from file arduinobot_remote/ArduinobotTaskActionGoal.msg
// DO NOT EDIT!


#ifndef ARDUINOBOT_REMOTE_MESSAGE_ARDUINOBOTTASKACTIONGOAL_H
#define ARDUINOBOT_REMOTE_MESSAGE_ARDUINOBOTTASKACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arduinobot_remote
{
template <class ContainerAllocator>
struct ArduinobotTaskActionGoal_
{
  typedef ArduinobotTaskActionGoal_<ContainerAllocator> Type;

  ArduinobotTaskActionGoal_()
    : task_number(0)  {
    }
  ArduinobotTaskActionGoal_(const ContainerAllocator& _alloc)
    : task_number(0)  {
  (void)_alloc;
    }



   typedef int64_t _task_number_type;
  _task_number_type task_number;





  typedef boost::shared_ptr< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ArduinobotTaskActionGoal_

typedef ::arduinobot_remote::ArduinobotTaskActionGoal_<std::allocator<void> > ArduinobotTaskActionGoal;

typedef boost::shared_ptr< ::arduinobot_remote::ArduinobotTaskActionGoal > ArduinobotTaskActionGoalPtr;
typedef boost::shared_ptr< ::arduinobot_remote::ArduinobotTaskActionGoal const> ArduinobotTaskActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator1> & lhs, const ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.task_number == rhs.task_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator1> & lhs, const ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arduinobot_remote

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a44f0e3523e87134465bfb1a1ffe53cc";
  }

  static const char* value(const ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa44f0e3523e87134ULL;
  static const uint64_t static_value2 = 0x465bfb1a1ffe53ccULL;
};

template<class ContainerAllocator>
struct DataType< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arduinobot_remote/ArduinobotTaskActionGoal";
  }

  static const char* value(const ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"int64 task_number\n"
;
  }

  static const char* value(const ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArduinobotTaskActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arduinobot_remote::ArduinobotTaskActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "task_number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.task_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUINOBOT_REMOTE_MESSAGE_ARDUINOBOTTASKACTIONGOAL_H
