// Generated by gencpp from file arduinobot_remote/ArduinobotTaskResult.msg
// DO NOT EDIT!


#ifndef ARDUINOBOT_REMOTE_MESSAGE_ARDUINOBOTTASKRESULT_H
#define ARDUINOBOT_REMOTE_MESSAGE_ARDUINOBOTTASKRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arduinobot_remote
{
template <class ContainerAllocator>
struct ArduinobotTaskResult_
{
  typedef ArduinobotTaskResult_<ContainerAllocator> Type;

  ArduinobotTaskResult_()
    : success(false)  {
    }
  ArduinobotTaskResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> const> ConstPtr;

}; // struct ArduinobotTaskResult_

typedef ::arduinobot_remote::ArduinobotTaskResult_<std::allocator<void> > ArduinobotTaskResult;

typedef boost::shared_ptr< ::arduinobot_remote::ArduinobotTaskResult > ArduinobotTaskResultPtr;
typedef boost::shared_ptr< ::arduinobot_remote::ArduinobotTaskResult const> ArduinobotTaskResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator1> & lhs, const ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator1> & lhs, const ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arduinobot_remote

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arduinobot_remote/ArduinobotTaskResult";
  }

  static const char* value(const ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"bool success\n"
;
  }

  static const char* value(const ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArduinobotTaskResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arduinobot_remote::ArduinobotTaskResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUINOBOT_REMOTE_MESSAGE_ARDUINOBOTTASKRESULT_H
