name: Manipulator_Robot

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: run the project tasks
        run: |
          cd arduinobot_ws
          source /opt/ros/noetic/setup.bash
          source devel/setup.bash
          catkin_make
