name: Manipulator_Robot

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: installing ROS Noetic - moveit
        run: |
          sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
          sudo apt install curl
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo apt update
          sudo apt install ros-noetic-desktop-full
          source /opt/ros/noetic/setup.bash
          echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
          source ~/.bashrc
          sudo apt install python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential
          sudo apt install python3-rosdep
          sudo rosdep init
          rosdep update
          sudo apt install ros-noetic-moveit

      - name: run the project tasks
        run: |
          cd arduinobot_ws
          catkin_make
          source devel/setup.bash
